
site_name: MusicOnto
site_url: https://MusicOnto.com/

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    watch:
      - MusicOnto/MusicOnto

nav:
    - "Home": test_1.md
    - "Test": test_2.md
    - "ref": my_page.md


theme:
    name: "mkdocs"







