site_name: MusicOnto
site_url: https://MusicOnto.com/

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    watch:
      - MusicOnto/

nav:
    - "Home": index.md
    - "Sentics": Sentics.md

theme:
    name: "readthedocs"







