
site_name: MusicOnto
site_url: https://MusicOnto.com/

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    watch:
      - MusicOnto/Sentics.py

nav:
    - "Home": my_page.md

theme:
    name: "mkdocs"







